// import axios from 'axios'; // Removed axios
import { Platform } from 'react-native';
import { BASE_URL } from '../config/host';

// BASE_URL is auto-generated by scripts/update-host.js at dev server startup.
// Run `npm start` (or npm run android/ios) and it will always use your current LAN IP.
console.log('API Base URL configured as:', BASE_URL);


// Helper to mimic Axios response structure
const fetchClient = async (endpoint: string, options: RequestInit & { isFormData?: boolean } = {}) => {
    const url = `${BASE_URL}${endpoint}`;
    const { isFormData, ...restOptions } = options as any;

    const headers: any = {
        'Content-Type': 'application/json',
        ...(restOptions.headers || {}),
    };

    // If body is FormData, let fetch set the multipart Content-Type with boundary
    if (isFormData) {
        delete headers['Content-Type'];
    }

    const config = {
        ...restOptions,
        headers,
    };

    try {
        const response = await fetch(url, config);
        const data = await response.json().catch(() => ({}));

        if (!response.ok) {
            const error: any = new Error('API Error');
            error.response = {
                data,
                status: response.status,
            };
            throw error;
        }

        return {
            data,
            status: response.status,
        };
    } catch (error: any) {
        if (error.response) throw error; // Re-throw if it's our structured error
        // Network errors or other
        console.error("Fetch error:", error);
        throw error;
    }
};

export const authAPI = {
    login: (data: any) => fetchClient('/login', { method: 'POST', body: JSON.stringify(data) }),
    register: (data: any) => fetchClient('/register', { method: 'POST', body: JSON.stringify(data) }),
    verifyOTP: (data: any) => fetchClient('/verify-otp', { method: 'POST', body: JSON.stringify(data) }),
    sendOTP: (data: any) => fetchClient('/send-otp', { method: 'POST', body: JSON.stringify(data) }),
};

export const doctorAPI = {
    register: (data: any) => fetchClient('/doctor/register', { method: 'POST', body: JSON.stringify(data) }),
    login: (data: any) => fetchClient('/doctor/login', { method: 'POST', body: JSON.stringify(data) }),
};

export const chatAPI = {
    sendMessage: (message: string, user_phone: string = "") => fetchClient('/chat', { method: 'POST', body: JSON.stringify({ message, user_phone }) }),
    uploadFile: (formData: FormData) => fetchClient('/upload', {
        method: 'POST',
        body: formData,
        isFormData: true,
    } as any),
};

export const statsAPI = {
    saveStats: (stats: any) => fetchClient('/save-stats', { method: 'POST', body: JSON.stringify(stats) }),
};

export const reportsAPI = {
    /** Upload a file and create a report record in Supabase. */
    upload: (formData: FormData) => fetchClient('/upload-report', {
        method: 'POST',
        body: formData,
        isFormData: true,
    } as any),

    /** List all reports for a given user (newest first). */
    list: (userPhone: string) => fetchClient(`/reports/${encodeURIComponent(userPhone)}`, { method: 'GET' }),

    /** Get full details (including extracted data) for a single report. */
    detail: (reportId: string) => fetchClient(`/reports/detail/${encodeURIComponent(reportId)}`, { method: 'GET' }),

    /** Get aggregated lab history for all parameters across all reports. */
    labHistory: (userPhone: string) => fetchClient(`/api/lab-history/${encodeURIComponent(userPhone)}`, { method: 'GET' }),
};

// Default export if needed, though we should prefer named exports
export default {
    ...authAPI,
    ...doctorAPI,
    ...chatAPI,
    ...statsAPI,
    ...reportsAPI,
};
