/**
 * update-host.js
 *
 * Automatically detects the machine's LAN IP address and writes it to
 * src/config/host.ts so the React Native app always points to the
 * correct backend server without manual edits.
 *
 * Run automatically via: npm start / npm run android / npm run ios
 */

const os = require('os');
const fs = require('fs');
const path = require('path');

const PORT = 9000;
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'config', 'host.ts');

function getLocalIP() {
    const interfaces = os.networkInterfaces();
    for (const name of Object.keys(interfaces)) {
        for (const iface of interfaces[name]) {
            // Skip loopback (127.x.x.x) and non-IPv4
            if (iface.family === 'IPv4' && !iface.internal) {
                return iface.address;
            }
        }
    }
    return '127.0.0.1'; // fallback
}

const ip = getLocalIP();
const baseUrl = `http://${ip}:${PORT}`;

const content = `// AUTO-GENERATED by scripts/update-host.js — do not edit manually.
// Re-generated every time you run: npm start / npm run android / npm run ios
export const BASE_URL = "${baseUrl}";
`;

// Ensure config directory exists
const configDir = path.dirname(OUTPUT_FILE);
if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
}

fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
console.log(`✅  Host IP detected: ${ip}`);
console.log(`✅  BASE_URL set to:  ${baseUrl}`);
console.log(`✅  Written to:       ${OUTPUT_FILE}`);
